services:
  - type: web
    name: rti-collection
    runtime: python
    plan: free
    autoDeploy: false
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT